import regex

schema BaseObject:

    # Unique identifier
    id: str
    # Last update timestamp
    updatedAt?: str
    # Creation timestamp
    createdAt?: str

    check:
        regex.match(id, r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
        regex.match(updatedAt, r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$")
        regex.match(createdAt, r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$")