schema AS3_API_Request_oneOf_4Mixin:


schema AS3_API_Request:
    one_of:
        - AS3_API_Request_oneOf_0Mixin
        - AS3_API_Request_oneOf_1Mixin
        - AS3_API_Request_oneOf_2Mixin
        - AS3_API_Request_oneOf_3Mixin
        - AS3_API_Request_oneOf_4Mixin


schema AS3_API_Request_oneOf_0Mixin:


schema AS3_API_Request_oneOf_1Mixin:


schema AS3_API_Request_oneOf_2Mixin:


schema AS3_API_Request_oneOf_3Mixin:


